### ISSUE TITLE
Parsing of VNN-Comp 2022 instances

### ISSUE THREAD

**Issue by phK3** [vas-group-imperial/VeriNet#2] opened 2022-12-21 10:27 UTC
I tried to run VeriNet on the `dubins_rejoin` instances of this year's VNN-Comp using
`benchmark(result_path, benchmark_path, instances_csv_path, input_shape=(8,), transpose_fc_weights=False)`, but the parsing of the vnnlib-properties failed.

For `dubinsrejoin_case_safe_0.vnnlib` the following error is thrown:

`ValueError: And-expression: ['(<=', 'Y_1', 'Y_0)(<=', 'Y_2', 'Y_0)(<=', 'Y_3', 'Y_0)(<=', 'Y_4', 'Y_6)(<=', 'Y_5', 'Y_6)(<=', 'Y_7', 'Y_6'] not recognised`

How can I fix this?
Thank you.

**Comment by pat676** [comment] 2022-12-21 11:01
Hi, thanks for the feedback!

There seems to be a bug where the VNNLib parser requires spaces between closing and opening parenthesis. I've pushed a fix to the issue #2 branch (commit 09214894ec87144df1a8a270a0f271bdc5276660). Could you please pull that commit, and check whether this solves the problem? If so, I'll merge the fix into the main branch. 

Also, please note that this is not the same version of VeriNet as used in VNNCOMP 22; the version used in VNNCOMP 22 is unfortunately not public. Thus some performance difference is to be expected.

**Comment by phK3** [comment] 2022-12-21 16:25
Thanks for the quick reply!
Parsing the vnnlib file works fine.

Parsing the `dubinsrejoin.onnx` however also seems to cause an error.
I'll open another issue.

**Comment by pat676** [comment] 2022-12-22 09:48
Confirmed fixed in merge commit 885e51983f9078bce5a251b922bed6bf329539e3, closing.

**Closed as completed by pat676** 2022-12-22 09:48 UTC
